name = "pwrup-site"
compatibility_date = "2024-12-20"

# Static site configuration - serve everything from dist/ as static assets
[assets]
directory = "./dist"

# Optimize compression and caching
[[assets.rules]]
globs = ["**/*.js", "**/*.css", "**/*.html", "**/*.json", "**/*.xml", "**/*.txt"]
headers = { "Cache-Control" = "public, max-age=31536000, immutable" }

[[assets.rules]]
globs = ["**/*.woff2", "**/*.woff", "**/*.ttf", "**/*.otf"]
headers = { "Cache-Control" = "public, max-age=31536000, immutable" }

[[assets.rules]]
globs = ["**/*.webp", "**/*.jpg", "**/*.jpeg", "**/*.png", "**/*.gif", "**/*.svg", "**/*.ico"]
headers = { "Cache-Control" = "public, max-age=31536000, immutable" }
